### ISSUE TITLE
Prevent circular update loops

### ISSUE THREAD

**Issue by snarky-snark** [snarky-snark/home-assistant-variables#1]
An infinite update loop can occur if a variable appears in its own `value_template` and the variable is set to update based on its own state changes. There are use cases where it is useful for a variable to appear in its own `value_template`. For example,
```yaml
var:
  toggle_counter:
    initial_value: 0
    value_template: "{{ var.toggle_counter | int + 1 }}"
    tracked_entity_id: input_boolean.foo
```
In this case, `var.toggle_counter` is only updated on changes to `input_boolean.foo`, however, there are situations that warrant listening for the state changes of the variable itself.

In those cases we need to prevent the loop from happening.

A few options to fix this:
1. Validate input to prevent `value_template` and `tracked_entity_id` from both containing the var. 
2. Allow this situation to occur, but don't update a var's `self._value` if the reason for the update was a state change event for itself.

I'm leaning towards 2 since it allows for other var attributes to be updated whenever the value of the var changes.
