### ISSUE TITLE
global versus local...

### ISSUE THREAD

**Issue by pvklink** [snarky-snark/home-assistant-variables#104]

**Comment by pvklink** [comment]
Can variables made global, even if they are declared in a choose scenario?
In the below (part of my) script i update the var e1 two times, At the start and when a condition matches...
My problem is that i want to overule the first declaration within a choose construct, at the end of the script the first declaration is available...

What am i doing wrong"

I use he latest HASS beta on a docker on rpi 4b with the latest OS.


sequence:
  - service: var.set
    data:
      entity_id: var.e1
      value: 1 START
  - service: notify.persistent_notification
    data:
      message: DEBUG IRRIGATIE 1 error {{states('var.e1')}}
      title: DEBUG IRRIGATIE 1
  - choose:
      - conditions:
          - or:
              - condition: template
                value_template: "{{ debug == 'scenes_unlock' }}"
              - and:
                  - condition: template
                    value_template: "{{ debug == 'scenes_single' }}"
                  - condition: template
                    value_template: "{{ actiontrigger == 'input_boolean.scene_opstaan' }}"
        sequence:
          - service: var.set
            data:
              entity_id: var.e1
              value: 2
  - service: notify.persistent_notification
    data:
      message: DEBUG IRRIGATIE 2 error {{states('var.e1')}}
      title: DEBUG IRRIGATIE 1
mode: parallel
max: 20
`

**Comment by danielbrunt57** [comment]
#1. A particular variable only exists once (i.e. globally).  You can't have two different instances of the same named variable & different values.
#2. Review your automation/script traces to make sure your code is doing what you want.
#2. Format your code with the code wrapper: <>.  It should then look something like this:
My code:
```
service: var.set
data:
  entity_id: var.batteries_replaced
  attributes:
    "{{ trigger.entity_id }}": "{{as_timestamp(now()) | timestamp_custom('%Y-%m-%d') }}"
```
I don't know if your code is correct or not.
This is my guess at what your code's `choose:` might look like...
```
- choose:
    - conditions:
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ debug == 'scenes_unlock' }}"
            - condition: and
              conditions:
                - condition: template
                  value_template: "{{ debug == 'scenes_single' }}"
                - condition: template
                  value_template: "{{ actiontrigger == 'input_boolean.scene_opstaan' }}"
      sequence:
        service: var.set
        data:
          entity_id: var.e1
          value: 2
```
