### ISSUE TITLE
use var for card colors

### ISSUE THREAD

**Issue by L0bit0** [snarky-snark/home-assistant-variables#106]
Hi

to be honest not sure if this is an issue or I am just trying to use var incorrectly, let me explain

I have different cards to show entities graphs on different dashboards.
I would like to minimize the effort when I want to change the color of an specific entities.
I have created a variable with the color name I want on my entity:
```
temp_ext_color:
      friendly_name: 'temp_ext_color'
      initial_value: '#FF00FF'
      icon: mdi:palette
```

and I can read the value from the card configuration:
![image](https://github.com/snarky-snark/home-assistant-variables/assets/10359623/2cfb70be-c8bd-4da2-bbc4-3293f4655471)

But the color is not updated propertlly: it is black and shold be ink on this case...

NOTE: I have tried with '''#FF00FF''' and '#FF00FF', just in case quotes was the issue.

I am using right? can be used for this? if not, any idea what i can do?

thansk
