### ISSUE TITLE
Value template problem after 0.15.1 upgrade

### ISSUE THREAD

**Issue by blackie333** [snarky-snark/home-assistant-variables#109]
Hello,
use variables for holding some long-term values which worked great.
After latest upgrade my variables values became reset to empty string after HA restart.
Seems like value automatic update via template won't work as before for tracked_entity updates.
I want to return old value if group state condition is not met but old value gets lost.
please fix this.

var:
  last_motion_time:
    friendly_name: "Last Motion Time"
    restore: true
    value_template: >-
      {% if is_state('group.grp_motion_sensors_all', "on") %}
        {{ states.sensor.date_time.state }}
      {% else %}
        {{ states('var.last_motion_time') }}
      {% endif %}
    icon: mdi:motion-sensor-off
    tracked_entity_id:
      - group.grp_motion_sensors_all

  last_alarm_time:
    friendly_name: "Last Alarm Time"
    restore: true
    value_template: >-
      {% if is_state('alarm_control_panel.home_alarm', "triggered") %}
        {{ states.sensor.date_time.state }}
      {% else %}
        {{ states('var.last_alarm_time') }}
      {% endif %}
    icon: mdi:alarm-light-off-outline
    tracked_entity_id:
      - alarm_control_panel.home_alarm

**Comment by snarky-snark** [comment]
v0.15.1 was broken. Try v0.15.2.

**Comment by blackie333** [comment]
v0.15.2 tested but unfortunately issue remains. 
Template values still got reset during HA Core restart.

**Comment by estegewr** [comment]
After upgrading to v0.15.1 I encountered the problems reported in #107. The fix with v0.15.2 restored most of the logic, but not the persistence of values and attributes as reported by @blackie333 . I'm happy to test or verify further if I get some pointers on what to look for.

**Comment by nm20220210** [comment]
same error in v0.15.1 &  v0.15.2 
variable value is empty
go back to old release v0.15.0

```
alias: vartest
description: ""
trigger: []
condition: []
action:
  - service: var.set
    data:
      entity_id: var.pmx152
      value: test
  - if:
      - condition: state
        entity_id: var.pmx152
        state: test
    then:
      - service: notify.persistent_notification
        metadata: {}
        data:
          message: OK
    else:
      - service: notify.persistent_notification
        metadata: {}
        data:
          message: NIO
mode: single

```
