### ISSUE TITLE
Restore attribute values if HA starts

### ISSUE THREAD

**Issue by estegewr** [snarky-snark/home-assistant-variables#112]
The default behavior of the module is to restore the variable value after HA restarts, whcih can also be requested with the restore option in conguration.yaml

```
var:
  weather_forecast:
    friendly_name: "Weather forecast for next 8 hours"
    restore: true
```

While HA is running, I set the variable value and some attributes with the service call:

```
service: var.set
data:
  entity_id: var.weather_forecast
  value: sunny
  attributes:
    TempMax: 20.1
    TempMin: 11.4
```

Value and attributes are set successfully. But HA restart will only restore the value, not the attributes
With a trick, you can also get this done: By setting an initial value of the attributes in configuration.yaml:

```
var:
  weather_forecast:
    friendly_name: "Weather forecast for next 8 hours"
    restore: true
    attributes:
      TempMin: ""
      TempMax: ""
```

This was probably not the intended way in which the initial setting of the attributes had played out. Starting with v0.15.1 and still in 0.15.2 each HA restart initializes the value of the attribute with the configured value in configiuration.yaml. Unfortunately, this also means, that I cannot restore any updated attribute.

Therefore, I would like to ask for a configuration option to define attributes for further proceeding/restoring if this cannot be figured out automatically browsing through all available non-standard attributes.
