### ISSUE TITLE
Using !include folders

### ISSUE THREAD

**Issue by geejayem99** [snarky-snark/home-assistant-variables#17]
Does this component allow the use of include folders to allow splitting configuration out to separate files? I've tried what I think should work and it appears not, but maybe I'm doing it wrong.

If, in configuration.yaml, I have:

```
var:

  min_temp_var:
    friendly_name: 'Overnight Minimum'
    icon: mdi:thermometer-low
    tracked_entity_id: sensor.outside_temp
    unit_of_measurement: '°C'
    value_template: >
      {% if float(states('sensor.outside_temp')) < float(states('var.min_temp_var')) %}
      {{float(states('sensor.outside_temp'))}}
      {%- else -%}
      {{float(states('var.min_temp_var'))}}
      {%- endif %}

  max_temp_var:
    friendly_name: 'Daytime Maximum'
    icon: mdi:thermometer-high
    tracked_entity_id: sensor.outside_temp
    unit_of_measurement: '°C'
    value_template: >
      {% if float(states('sensor.outside_temp')) > float(states('var.max_temp_var')) %}
      {{float(states('sensor.outside_temp'))}}
      {%- else -%}
      {{float(states('var.max_temp_var'))}}
      {%- endif %}

```

It works as expected, but having:

`var: !include_dir_merge_list var`

in configuration.yaml and adding the code from min_temp_var: onwards (keeping same indentation) to a file called min_max_temp.yaml in a folder 'var' under the folder 'config', I get 'Setup failed for var: Integration failed to initialize.' in the log and a notification of the same. 

HomeAssistant 0.103.4 hassio install on RPi3
variable v0.9.2 via HACS

**Comment by snarky-snark** [comment]
As far as I am aware, those include statements are independent from component logic, so it is I unlikely that your issue is a problem in the var component.

Looking at the [documentation](https://www.home-assistant.io/docs/configuration/splitting_configuration/#example-include_dir_merge_list), it seems your issue is a lack of hypens in front of your declared variables. You need to add hyphens to make the entries into a list.

```yaml
- min_temp_var:
    friendly_name: 'Overnight Minimum'
    icon: mdi:thermometer-low
    tracked_entity_id: sensor.outside_temp
    unit_of_measurement: '°C'
    value_template: >
      {% if float(states('sensor.outside_temp')) < float(states('var.min_temp_var')) %}
      {{float(states('sensor.outside_temp'))}}
      {%- else -%}
      {{float(states('var.min_temp_var'))}}
      {%- endif %}

- max_temp_var:
    friendly_name: 'Daytime Maximum'
    icon: mdi:thermometer-high
    tracked_entity_id: sensor.outside_temp
    unit_of_measurement: '°C'
    value_template: >
      {% if float(states('sensor.outside_temp')) > float(states('var.max_temp_var')) %}
      {{float(states('sensor.outside_temp'))}}
      {%- else -%}
      {{float(states('var.max_temp_var'))}}
      {%- endif %}
```
