### ISSUE TITLE
Feature Request: Toggle Service

### ISSUE THREAD

**Issue by jhotmann** [snarky-snark/home-assistant-variables#22]
There are some variables that I store as true/false (could also be stored as 1/0 or on/off) and it would be really handy if there was a service call var.toggle that would convert a variable to it's opposite to make the UI for buttons a lot cleaner.

**Comment by snarky-snark** [comment]
That would seem to clean up some boilerplate for those instances. I'm happy to accept a pull request. Should be easy to implement, just might take some time to test. 

On the other hand, it should be pretty simple and clean to do this with the set service as it stands. Here's an untested example to give an idea.
```yaml
action:
      service: var.set
      data_template:
        entity_id: var.foo
        value: {{ not (states('var.foo') | bool) }}
```

compared to

```yaml
action:
      service: var.toggle
      data:
        entity_id: var.foo
```

**Comment by jhotmann** [comment]
I kept getting some filter error when trying to parse the boolean with `| bool` so I ended up getting it working like this.

```yaml
    hold_action:
      action: call-service
      service: var.set
      service_data:
        entity_id: var.bedroom_motion_activation
        value_template: >-
          {% if is_state('var.bedroom_motion_activation', 'True') %} False {%
          else %} True {% endif %}
```
