### ISSUE TITLE
Variable stored as a string - but need it as a datetime

### ISSUE THREAD

**Issue by septeven** [snarky-snark/home-assistant-variables#24]
Hi,
I'm trying to store a `datetime` variable using your integration.

Unfortunately, it seems to be stored as a `string` instead of a `datetime` which make impossible the use of `relative_time()` function in template.

**Variable code:**
```yaml
var:
  last_check_internet_status:
    icon: mdi:router-wireless
```
**Automation code (service part) - I tried both ways:**
```yaml
- service: var.set
    data:
      entity_id: var.last_check_internet_status
      value_template:  "{{ now() }}"
```
      
```yaml
- service: var.set
    data_template:
      entity_id: var.last_check_internet_status
      value: "{{ now() }}"
```

**This template won't work because it's a string, not a datetime object.**
```yaml
{{ relative_time(states('var.last_check_internet_status')) }}
```

Please let me know if I'm doing something wrong or if you can provide a workaround/improvement to this ?

Thanks
