### ISSUE TITLE
Accept string or list for `tracked_event_type`

### ISSUE THREAD

**Issue by snarky-snark** [snarky-snark/home-assistant-variables#3]
For parity with `tracked_entity_id`, `tracked_event_type` should accept a string that denotes either a single event type or multiple event types separated by commas.

Examples:
```yaml
# single event type as string
tracked_event_type: 'foo_event'

# multiple event types as string 
tracked_event_type: 'foo_event,bar_event'

# one or more event types as a list (already supported)
tracked_event_type:
  - 'foo_event'
  - 'bar_event'
```
