### ISSUE TITLE
Assign a python result in a var

### ISSUE THREAD

**Issue by Audiothor** [snarky-snark/home-assistant-variables#38]
Hi
I have a simple python script
`dt=datetime.now()
datej="%02d/%02d/%04d %02d:%02d:%02d" % (dt.day,dt.month,dt.year,dt.hour,dt.minute,dt.second)
print(datej)`
And I want this print result to be assigned via var.set or var.update from one of my variable...
My variable is defined like 
`var:
  datep:
    friendly_name: 'Date detect move'
    initial_value: '-'
    icon: mdi:video`
Is it possible ? How to proceed ?
Thanks for your help.

**Comment by snarky-snark** [comment]
I think something like this should work.

Assign the variable in python script:
```python
# ...
var = data.get("var")
service_data = {"entity_id": var, "value": datej}
    hass.services.call("var", "set", service_data, False)
```
Pass in the variable to assign when you call your script in yaml:
```yaml
service: python_script.your_script
  data:
    var: var.datep
```

Reference: https://www.home-assistant.io/integrations/python_script/#calling-services

**Comment by snarky-snark** [comment]
You can also do the following in YAML if you just want to assign a timestamp to a var.
```yaml
- service: var.set
  data_template:
          entity_id: var.datep
          value: "{ now() }"
```
