### ISSUE TITLE
Question about using secrets in variables

### ISSUE THREAD

**Issue by nobwyn** [snarky-snark/home-assistant-variables#43]
Hi there,

I was wondering if it is possible to secrets as values with this component? 

I've tried something like this:

```
var:
  my_var1:
    value_template: !secret some_password
```

but when I check the `var.my_var1` state via _developer tools_ it contains a value of "`unknown`" ...

This would be quite useful as then it would be possible to pass/access some secrets from templates via `states` object.

**Comment by snarky-snark** [comment]
I have a feeling this doesn't work because you are using value_template instead of initial_value.

In any case, I think the processing of secrets is something that home assistant does before it reaches the var component, so the var component doesn't have the ability to read secrets itself.

**Comment by snarky-snark** [comment]
I'll leave this open in case someone who knows more wants to chime in.

**Comment by mvsjes2** [comment]
It should actually work. Secrets and includes are resolved automatically as the yaml config is initially loaded. It's part of the yaml read process very early on and should work for any key. var should not even be aware that a secret had been coded. I'd double check your config. Try running the check_config script.

**Comment by nobwyn** [comment]
I did double-check the configuration with `value_template` as well as with `initial_value` - unfortunately it doesn't work for me...

Here is my simple configuration:

```
var:
  my_var1:
    initial_value: !secret some_password
    # also:
    # value_template: !secret some_password

sensor:
  - platform: template
    sensors:
      my_var2:
        value_template: !secret some_password
```

and what I see in developer tools:

![image](https://user-images.githubusercontent.com/8455481/103576490-861c4e00-4ed3-11eb-9c41-f4326d4a7c25.png)
