### ISSUE TITLE
Variables never change from 0

### ISSUE THREAD

**Issue by steerage250** [snarky-snark/home-assistant-variables#49]
I am a new Home Assistant user.  I think Variables is just what I need, so installed v10.0 via HACS.

The definition of the variable in configuration.yaml seems to work because I can display it in LoveLace, and reference them in automations etc - but I can't get the value to change.  I have set it with an initial_value, and also have an automation (that is triggering) that is using var.set - still zero.

(edited to format the code correclty)
```
var:
  pv_output_to_use:
    friendly_name: "PV output to use"
    icon: mdi:bug
    initial_value: 123
    value_template:
       "{{ 234 }}"


automation set_PV_power_in_test_mode:
  alias: "Set PV power in Test Mode"
  trigger:
    platform: template
    value_template: "{{ is_state('input_boolean.test_contactor', 'on') }}"
  condition:
    - condition: template
      value_template: "{{ is_state('input_boolean.test_mode', 'on') }}"  
  action:
    - service: var.set
      data:
        entity_id: pv_output_to_use
        value: 100
```

**Comment by steerage250** [comment]
further to the above, I can change the value using the Developer Tools, then restart the Pi - and the value does not change back to the initial_value

**Comment by snarky-snark** [comment]
> I am a new Home Assistant user. I think Variables is just what I need

You might want to look into the [NodeRed add-on](https://community.home-assistant.io/t/home-assistant-community-add-on-node-red/55023) for Home Assistant. It's what I prefer for programming automations, and it seems more approachable than yaml. This var component is a bit of an abuse of the HA entity system, and it is cumbersome to use. 

> (I can't work-out how to get the code to format properly in this post!)

To format code blocks, wrap it with three backticks like so:
\```yaml
code goes here
\```

Regarding your config, there are a few issues I see.

1. Set `restore: false` if you want to use the `initial_value` each time home assistant starts. By default, the previous value of the variable is restored on startup. 

1. `value_template: "{{ 234 }}"` is only evaluated when tracked entities are updated or tracked events fire. You must specify `tracked_entity_id` or `tracked_event_type`. \
  \
  You may also want to have a look at this ticket: https://github.com/snarky-snark/home-assistant-variables/issues/8#issuecomment-529436261  
  
    > Templates are only evaluated when a variable updates. Updates only occur automatically when a tracked_event_type fires or a tracked_entity_id state change occurs. If neither of those parameters is specified, then the variable and its templates will not update automatically. You can track the homeassistant_start event to update automatically on startup.
  
    ```yaml
    tracked_event_type:
    - homeassistant_start
    ```  
    That will force an update on start using the value_template.

1. Last, are you sure your automation is firing? Try replacing the `var.set` service with a notification to verify this.
    ```yaml
    action:
      service: persistent_notification.create
      data:
        title: Test
        message: "test"
    ```

**Comment by steerage250** [comment]
Thanks for your comments.  The automation is firing (I used your test method above).  Node Red looks interesting.  I have installed it and will experiment with it.

**Comment by snarky-snark** [comment]
What happens if you try to call the var.set service from the developer tools?

**Comment by steerage250** [comment]
I didn't realise you could do that.  I tried and it worked, so I randomly kept tweaking the format a bit until I finally got it to work with the following.  I think the key thing was that I hadn't prefixed my variable name with "var."
```
  action:
    - service: persistent_notification.create
      data:
        title: Test
        message: "setting pv_putput_to_use"
    - service: var.set
      entity_id: var.pv_output_to_use
      data:
        value: 345
```
Thanks very much for your help - I learnt a few things about HA in the process.
