### ISSUE TITLE
Error assigning a var to a plant config variable

### ISSUE THREAD

**Issue by JGAguado** [snarky-snark/home-assistant-variables#51]
Hi there,

I am trying to assign the conf variable min_moisture to the value contained in a home-assistant-variables. I already created the variable as:
```
var:
  tomatoes_min_moisture: 
    initial_value: 20
```

and then assigned in the plant definition (bringing it as an int):
```
plant:
  tomatoes:
    sensors:
      moisture: sensor.tomatoes_moisture
      battery: sensor.tomatoes_battery
      temperature: sensor.tomatoes_temperature
      conductivity: sensor.tomatoes_conductivity
      brightness: sensor.tomatoes_light_intensity
    min_moisture: "{{ states('var.tomatoes_min_moisture') | int }}"
```

but i get the following error:
```
Invalid config for [plant]: expected int for dictionary value @ data['plant']['tomatoes']['min_moisture']. Got "{{ states('var.tomatoes_min_moisture') | int }}". (See /config/configuration.yaml, line 12).
```

I would really appreciate any help,

BR
