### ISSUE TITLE
record history attributes ?

### ISSUE THREAD

**Issue by Mariusthvdb** [snarky-snark/home-assistant-variables#53]
Hi, 
please allow me a question and not raise an issue...
I have been using the other CC for variables https://github.com/rogro82/hass-variables since forever, to record the history of events (like motion). Although it is against the philosophy of Paulus/Balloob, who feels we shouldn't abuse the HA state machine for recording this, it does fill a gap HA doesnt provide.

I was wondering if your variable CC can do the same. If so, I probably would migrate, since you are still developing your CC, and @rogro82 seems to have abandoned ship.

below is the declaration. of a variable, and an automation updating is upon motion:

```
variable:
  outside_motion:
    value: No motion detected
    restore: true
    attributes:
      icon: mdi:exit-run
      friendly_name: Outside Motion

automation:
  - alias: Update Outside Motion
    id: Update Outside Motion
    trigger:
      platform: state
      entity_id:
        - binary_sensor.backdoor_buiten_sensor_motion
        - binary_sensor.driveway_buiten_sensor_motion
        - binary_sensor.garden_backyard_buiten_sensor_motion
        - etc etc
      to: 'on'
    condition:
      >
        {{trigger.to_state is not none and
          trigger.from_state is not none and
          trigger.to_state.state != trigger.from_state.state}}
    mode: restart
    action:
      - delay:
          seconds: 2
      - service: variable.set_variable
        data:
          variable: outside_motion
          attributes:
            history_1: "{{states('variable.outside_motion')}}"
            history_2: "{{state_attr('variable.outside_motion','history_1')}}"
            history_3: "{{state_attr('variable.outside_motion','history_2')}}"
            history_4: "{{state_attr('variable.outside_motion','history_3')}}"
            history_5: "{{state_attr('variable.outside_motion','history_4')}}"
            history_6: "{{state_attr('variable.outside_motion','history_5')}}"
            history_7: "{{state_attr('variable.outside_motion','history_6')}}"
            history_8: "{{state_attr('variable.outside_motion','history_7')}}"
            history_9: "{{state_attr('variable.outside_motion','history_8')}}"
            history_10: "{{state_attr('variable.outside_motion','history_9')}}"
          value: >
            {{trigger.to_state.name|replace(' buiten sensor motion','')}}:
            {{as_timestamp(trigger.to_state.last_changed)|timestamp_custom('%X')}}
```

please have a look to see if, and if yes how I could adapt this to your integration?
thanks if you would!
