### ISSUE TITLE
cannot retrieve the value of a variable in automation condition!

### ISSUE THREAD

**Issue by G-Christ** [snarky-snark/home-assistant-variables#54]
Hi,
I have now spent almost 2 days trying to resolve this myself but unfortunately did not succeed yet. I might be missing something essential

Here is what I am trying to do:

I have **sensor.latest_code** that holds the latest received binary signal from my motion sensors.
I have an **input_boolean.sensor_motion3**
I want to make an automation that when received code  = '111101110100101011100' then turn my input boolean  on 

My automation without the variable works fine:

```trigger:
  - platform: state
    entity_id: sensor.latest_code
condition:
  - condition: state
    entity_id: sensor.latest_code
    state: '111101110100101011100'
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.sensor_motion3
```

The automation works also fine if I use input_text entities.

But trying to replace the hardcoded value by the variable 

```
var:
  sensor_motion3_on:
    initial_value: '111101110100101011100'
```

and putting it in the automation like this don’t work.

```
trigger:
  - platform: state
    entity_id: sensor.latest_code
condition:
  - condition: state
    entity_id: sensor.latest_code
    state: states.var.sensor_motion3_on
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.sensor_motion3
```

I tried using 
```
var.sensor_motion3_on
states(‘var.sensor_motion3_on’)
var.sensor_motion3_on.state
```
and tried changing the way the value is set like
```
111101110100101011100
'111101110100101011100'
"111101110100101011100"
```
But still no luck?

Actually in this context, I am using the variables to hold global constants. It is just a way to gather these hardcoded values in one place instead og having them spread amongst various automations.
If another approach is more appropriate, please let me know.

I also noticed that the variable values do not reset to **initial_value** after HA restart but retains their valueu from before restart.

Any limitations I am not aware of? Or what did I miss or do wrong?

Thanks 😊

**Comment by snarky-snark** [comment]
initial_value is used to set the initial value of the variable, but the variable retains its state across restarts. That is intended behavior.

Do you have Developer Tools enabled in HA? I would use that to check the state of your sensor and your variable to verify that they are the same.

**Comment by G-Christ** [comment]
Hi,

Thanks for the quick response :)

I display both the sensor and the variable in my UI and can see that these are the same.

And yes I do have the Developer Tools enabled if you want me to do any verification.

**Comment by G-Christ** [comment]
Hello again, 

I figured out that the issue is that I am comparing the states of two entities, rather than one entity state  against a constant. 
So I have to use template instead of state condition😊

so changing to:

```
condition:
  - condition: template
    value_template: '{{ is_state(''sensor.latest_code'', states(''var.sensor_motion3_on'')) }}'
```

Works actually fine now :)

But my next step is to use blueprint based automations as I have many sensors.

And in this context I pass the variable as input parameter **on_code**, that can be referred to like **!input on_code**

I haven’t yet figured out how to do that in the template condition. 

The following don’t work.

```
condition:
  - condition: template
    value_template: '{{ is_state(''sensor.latest_code'', states(''!input on_code'')) }}'
```

Any Ideas?

**Comment by G-Christ** [comment]
I figured it out,

I first save the value from the input to a local variable, then can refer to that in my template condition like this:

this works:
```
variables:
  sensor_on_code: !input on_code
condition:
  - condition: template
    value_template: '{{ is_state(''sensor.latest_code'', states(sensor_on_code)) }}'
```
So, in fact this is not an issue with the home-assistant-variables but my lack of understanding on how to get around with comparing the values  of two entities in the automation template condition.

I close this issue.
