### ISSUE TITLE
Var custom_component retains old value

### ISSUE THREAD

**Issue by richard-c-howlett** [snarky-snark/home-assistant-variables#56]
Hi,

Having a problem with the “var” custom_component. I have it installed to track version numbers of modules/packages I write which then get displayed on my dashboard. I was using rogro82’s “variable” component but have recently changed to your one which appears to be a better component moving forward.

At the top of each package I have something like:

```
var:
  phones_as_webcams_version:
    friendly_name: "Phones as Webcams version"
    initial_value: "v1.15 (11/06/2021)"
    icon: mdi:history
```

When I make a code change I update the version and date. With the old “variable” component the new value was accepted and duly displayed. Since switching to your “var” component the variable doesn’t change even though initial_value is used to set it. The very first setting of the variable remains.

I’ve tried adding:

tracked_event_type: homeassistant_start

in an attempt to force it to re-assign the initial_value but it makes no difference.

What am I doing wrong?

Cheers
Rich
