### ISSUE TITLE
force_update option not working properly

### ISSUE THREAD

**Issue by nitobosch** [snarky-snark/home-assistant-variables#58]
Hello,

I've set a variable with _**force_update**_ option to true, becase I want to get water comsumption liters in that variable, so I need to record every history point, even if it has changed or not.

My declaration is that:
```
var:
  test_var_last1:
    restore: true
    force_update: true
    unit_of_measurement: litros
```
But when I receive two equal consecutive values, i've checked in the database and have founded that the second value has the _old_state_id_  column empty, so it causes that HA not counting that record when, for example, I declare a statistics sensor from it.

![image](https://user-images.githubusercontent.com/11455488/128595684-51a27256-0563-4dd0-8fda-b63a17cd1a91.png)
