### ISSUE TITLE
Ability to store an Array

### ISSUE THREAD

**Issue by downthedeck** [snarky-snark/home-assistant-variables#7]
Would be nice if i could store an Array. Tried to store the value rgb_color of the light component but that doesn't seem to work.

    - service: var.set
       data:
         entity_id: var.previous_rgb_color
         value_template: "{{ state_attr('light.hue_play_1', 'rgb_color') }}"

**Comment by snarky-snark** [comment]
Do you intend to set `value_template` or `value`?

Try the following.
```yaml
- service: var.set
  data_template:
    entity_id: var.previous_rgb_color
    value: "{{ state_attr('light.hue_play_1', 'rgb_color') }}"
```
Note that `data_template` must be used in order to evaluate any template strings that are passed to the service. By using `data` and `value_template` you are not setting the value, rather you are setting `value_template` to a template string that will only be evaluated and stored in `value` whenever the var is updated. This is a subtle but meaningful distinction.

Hopefully that helps!
