### ISSUE TITLE
variable entity is briefly removed when hot reloading

### ISSUE THREAD

**Issue by zanna-37** [snarky-snark/home-assistant-variables#74]
When I hot reload the configuration, a weird behavior happens.
When a variable is used in a state trigger, the trigger is fired from a state `null` [see **1**].
When used in a numeric state, an error is logged [see **2**]

I suspect that the underlying reason is that the variable entity is briefly removed and then re-added to home assistant. This causes all sorts of problems. Maybe a better approach would be to update the entity without removing it.

-----

### 1
In the automation with the state trigger:
```yaml
platform: state
entity_id:
  - var.my_var1
```

When I hot reload the configuration, the automation is triggered and this is the info found in the debug section:
Notice the strange `from_state: null`.

```yaml
trigger:
[...]
  platform: state
  entity_id: var.my_var1
  from_state: null # <--------------------------- HERE
  to_state:
    entity_id: var.my_var1
    state: '1'
    [...]
```

### 2
In the automation with a numeric trigger:

```yaml
platform: numeric_state
entity_id: var.my_var2
below: '100'
```

When I hot reload the configuration, this error is logged:

```
Logger: homeassistant.components.homeassistant.triggers.numeric_state
Source: components/homeassistant/triggers/numeric_state.py:188
[...]
Error in 'my automation' trigger: In 'numeric_state' condition: no entity specified
```
