### ISSUE TITLE
tracked_entity_id not working

### ISSUE THREAD

**Issue by Paytrix** [snarky-snark/home-assistant-variables#75]
Hey guys,

I dont't know if I did something wrong, or if this is still a bug. 
I am trying to listen to a change of an input_select helper, which throws me an error. 
If I try it with any other entity_id, it still doesn't work. How is that possible? 

Config:
```
var:
  select_manufacturer:
    friendly_name: "Manufacturer"
    icon: mdi:warehouse
    value_template: "{{ 1 }}"
    tracked_enitity_id: input_select.manufacturer
```

Error:
```
Invalid config for [var]: [tracked_enitity_id] is an invalid option for [var]. Check: var->var->select_manufacturer->tracked_enitity_id. (See /config/configuration.yaml, line 148).
```
