### ISSUE TITLE
Attributes have null as value

### ISSUE THREAD

**Issue by majkers** [snarky-snark/home-assistant-variables#77]
Hi,

here is my config:

```
var:
  gaz1:
    friendly_name: "Rachunek za gaz"
    entity_picture: '/local/rachunki/pgnig.png'  
    initial_value: '2022-07-11'
    attributes:
      do_zaplaty: '449,70 zł'
      czy_oplacony: 'nie'
```

And this is what I see in HA:

![image](https://user-images.githubusercontent.com/21099773/176386919-30c0d1f4-93c6-4ecc-b3f0-e5179b7f7225.png)

So attributes get null as value...

**Comment by majkers** [comment]
Maybe this is related?

`invalid key: "OrderedDict([('449,70 zł', None)])" in "/config/configuration.yaml", line 807, column 0`

**Comment by snarky-snark** [comment]
Perhaps a text encoding issue? What happens if you change `'449,70 zł'` to `'449,70`?

**Comment by majkers** [comment]
No, still the same

**Comment by vigilcoma** [comment]
Have the same issue with attributes

**Comment by snarky-snark** [comment]
> Have the same issue with attributes

If you post more details about your problem, we may have a better chance of determining the cause.

**Comment by vigilcoma** [comment]
Have this config
```
var:
  lexman_1_data:
    friendly_name: "Lexman 1 data"
    initial_value: '{"current_light": ""}'
    attributes:
      scene_1: '{{ {"counter": 1} }}'
      scene_2: '{{ {"counter": 2} }}'
      scene_3: '{{ {"counter": 3} }}'
      scene_4: '{{ {"counter": 4} }}'
```

Wanted to store simple json
