### ISSUE TITLE
varible for caller list results in value:  "[object Object]": null

### ISSUE THREAD

**Issue by Bram-diederik** [snarky-snark/home-assistant-variables#83]
I have a asterisk server and i want to get the last 5 callers in a display in home assistant. 
but i cant get the variable set with the call data.

```
alias: inkomende beller
description: ""
trigger:
  - platform: webhook
    webhook_id: sip_call_webhook_id
condition: []
action:
  - service: var.set
    data:
      entity_id: var.call1
      value: {{trigger.json.caller | regex_findall_index("\"(.+)\"|\<(.*)\>")  }}
```

it results in

```
  - service: var.set
    data:
      entity_id: var.call1
      value:
        "[object Object]": null

```

is trigger.json. supported. Or do i doing something wrong. (I can set other variables)
