### ISSUE TITLE
Attributes as Objects

### ISSUE THREAD

**Issue by maforshaw** [snarky-snark/home-assistant-variables#88]
It would be nice if var attributes could be optionally stored as objects instead of strings. For example, I use a var SQL query to return multiple records as a JSON array which is then stored in an attribute.

To then use this attribute later I need to deserialise every time with "from_json" which is not ideal.

I know this is possible because I was previously using the component [ha-sql_json](https://github.com/crowbarz/ha-sql_json) which says this:

>"It is already possible to access data elements within a JSON result with the core SQL integration in templates using the from_json filter, however doing this causes the JSON string to be deserialised every time that the template is evaluated which is exponentially inefficient for large query results."

To overcome this, if you look at the source code, it works out the object type as follows:

```
                    if isinstance(value, decimal.Decimal):
                        value = float(value)
                    if isinstance(value, datetime.date):
                        value = str(value)
                    try:
                        value_json = json.loads(value)
                        if isinstance(value_json, dict) or isinstance(value_json, list):
                            value = value_json
                    except (ValueError, TypeError):
                        pass
                    self._attributes[key] = value
```

This means a JSON string that is output from the SQL query is then stored in the attribute as a list (or dictionary, depending on content) with no need to deserialise later.

To maintain backwards compatibility, I guess you could either add a boolean property whether to automatically work it out as above or a property to specify the data type.

**Comment by jb1228** [comment]
You can actually do this already via templates (also works with the built-in sensor/binary_sensor templates).

Example:

``` yaml
var:
  my_var:
    friendly_name: Var with Attributes as Object and Array
    initial_value: 100
    attributes:
      my_object: >-
        {{ {
          'aaaa': 'value_aaaa',
          'bbbb': 'value_bbbb',
          'cccc': 'value_cccc'
        } }}
      my_array: >-
        {{ [
          'item1',
          'item2',
          'item3'
        ] }}
```

You can then access the values as normal:

- `{{ states.var.my_var.attributes.my_object }}`<br>Returns: `{'aaaa': 'value_aaaa', 'bbbb': 'value_bbbb', 'cccc': 'value_cccc'}`

- `{{ states.var.my_var.attributes.my_object.aaaa }}`<br>Returns: `value_aaaa`

- `{{ states.var.my_var.attributes.my_array }}`<br>Returns: `['item1','item2','item3']`

- `{{ states.var.my_var.attributes.my_array[0] }}`<br>Returns: `item1`
